### ISSUE TITLE
I don't know how this works, I can't find the exe format in the tutorial

### ISSUE THREAD

**Issue by kiana12007** [rafi1212122/PemukulPaku#1]
I don't know how this works, I can't find the exe format in the tutorial
不知道这个怎么用，教程里找不到exe格式

**Comment by rafi1212122** [comment]
[latest](https://github.com/rafi1212122/PemukulPaku/actions)

https://github.com/rafi1212122/PemukulPaku/assets/65438157/98b9b42b-8a9b-4930-a42b-9e4a075cbb5f
