### ISSUE TITLE
在公网上搭建，我无法访问服务端

### ISSUE THREAD

**Issue by ouhuangoaa** [rafi1212122/PemukulPaku#11]
在公网上搭建好了服务端，在外网客户端无法访问服务端，仅在本地内网生效

**Comment by rafi1212122** [comment]
![image](https://github.com/rafi1212122/PemukulPaku/assets/65438157/9c14c725-b5b9-4b96-aa4f-eb8c1bf608f0)
试着检查config.json，用服务器的公共ip地址来改变它。

**Comment by ouhuangoaa** [comment]
好的，非常感谢
