### ISSUE TITLE
"for your account safety, please re-enter your password"(in chinese) while login.

### ISSUE THREAD

**Issue by czy20010112** [rafi1212122/PemukulPaku#6]
win 11, game version 6.7.0(5140) using  chinese client.  i don't kown why.......maybe i should use globel client?

**Comment by czy20010112** [comment]
using fillder as proxy, and the server cmd has shown some requests.

**Comment by wcjqwq** [comment]
First, use the international server to download the client using ASIA's launcher, then enter the game's resources, and then exit and hang it to enter the game

**Comment by wcjqwq** [comment]
If the descent is slow, you can hang the node
[https://honkaiimpact3.hoyoverse.com/asia/zh-cn/download](ASIA)

**Comment by czy20010112** [comment]
> If the descent is slow, you can hang the node [ASIA](https://honkaiimpact3.hoyoverse.com/asia/zh-cn/download)

got that, trying.( and mitmproxy does fix the issue though can't use with 6.7)

**Comment by czy20010112** [comment]
> First, use the international server to download the client using ASIA's launcher, then enter the game's resources, and then exit and hang it to enter the game

i downloaded the amercian client, download all resources , open the server ,run mitmproxy, and succeed in login it, but it end with the" miss a part of avatardata.json" in the server's cmd. and can't enter the game...  i'm sure that game version is 6.6(4xxx)... don't know how to solve it
i just open bh3.exe after finishing downloading all resources. does it matter?
try with south asia client tomorrow.

**Comment by czy20010112** [comment]
SOLVED !!!! CAUTION!!!
the guide tell me to put recource in the common folder buttttttttt  in face it's wrong , copy(?) it outside common can solve it

**Comment by sagilio** [comment]
> > If the descent is slow, you can hang the node [ASIA](https://honkaiimpact3.hoyoverse.com/asia/zh-cn/download)
> 
> got that, trying.( and mitmproxy does fix the issue though can't use with 6.7)

May I ask if your issue is solved? I also use the Asia version and mitmproxy. but the game still throw  `for your account safety, please re-enter your password`. I'm not sure what this problem is about…

**Comment by czy20010112** [comment]
> > > If the descent is slow, you can hang the node [ASIA](https://honkaiimpact3.hoyoverse.com/asia/zh-cn/download)
> > 
> > 
> > got that, trying.( and mitmproxy does fix the issue though can't use with 6.7)
> 
> May I ask if your issue is solved? I also use the Asia version and mitmproxy. but the game still throw `for your account safety, please re-enter your password`. I'm not sure what this problem is about…

solved . do you trust ur ca cert? use proxy to mitm.it to downlowd and trust.

**Comment by sagilio** [comment]
> > > > If the descent is slow, you can hang the node [ASIA](https://honkaiimpact3.hoyoverse.com/asia/zh-cn/download)
> > > 
> > > 
> > > got that, trying.( and mitmproxy does fix the issue though can't use with 6.7)
> > 
> > 
> > May I ask if your issue is solved? I also use the Asia version and mitmproxy. but the game still throw `for your account safety, please re-enter your password`. I'm not sure what this problem is about…
> 
> solved . do you trust ur ca cert? use proxy to mitm.it to downlowd and trust.

Trusted, I can find it at the cert manger.
![image](https://github.com/rafi1212122/PemukulPaku/assets/42855245/4b8604e1-b0bc-4b4c-a3f2-55485ca519a1)

**Comment by czy20010112** [comment]
> > > > > If the descent is slow, you can hang the node [ASIA](https://honkaiimpact3.hoyoverse.com/asia/zh-cn/download)
> 
> > > > 
> 
> > > > 
> 
> > > > got that, trying.( and mitmproxy does fix the issue though can't use with 6.7)
> 
> > > 
> 
> > > 
> 
> > > May I ask if your issue is solved? I also use the Asia version and mitmproxy. but the game still throw `for your account safety, please re-enter your password`. I'm not sure what this problem is about…
> 
> > 
> 
> > solved . do you trust ur ca cert? use proxy to mitm.it to downlowd and trust.
> 
> 
> 
> Trusted, I can find it at the cert manger.
> 
> ![image](https://github.com/rafi1212122/PemukulPaku/assets/42855245/4b8604e1-b0bc-4b4c-a3f2-55485ca519a1)
> 
> 

Make sure that:
1:the server opened on 80/443 successfully.
2:use the command in readme to activate proxy.py 
3:the system proxy setting is : 127.0.0.1:8080

If u still can't enter the game, go and see what is on the proxy and server cmd. Maybe there are some information.

For further help, u can go to the discord channel. We are here to help and there are many solutions of different situations.
以及咱们不会是俩国人飙英文吧草（

**Comment by sagilio** [comment]
> > > > > > If the descent is slow, you can hang the node [ASIA](https://honkaiimpact3.hoyoverse.com/asia/zh-cn/download)
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > got that, trying.( and mitmproxy does fix the issue though can't use with 6.7)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > May I ask if your issue is solved? I also use the Asia version and mitmproxy. but the game still throw `for your account safety, please re-enter your password`. I'm not sure what this problem is about…
> > 
> > 
> > > 
> > 
> > 
> > > solved . do you trust ur ca cert? use proxy to mitm.it to downlowd and trust.
> > 
> > 
> > Trusted, I can find it at the cert manger.
> > ![image](https://user-images.githubusercontent.com/42855245/244951030-4b8604e1-b0bc-4b4c-a3f2-55485ca519a1.png)
> 
> Make sure that: 1:the server opened on 80/443 successfully. 2:use the command in readme to activate proxy.py 3:the system proxy setting is : 127.0.0.1:8080
> 
> If u still can't enter the game, go and see what is on the proxy and server cmd. Maybe there are some information.
> 
> For further help, u can go to the discord channel. We are here to help and there are many solutions of different situations. 以及咱们不会是俩国人飙英文吧草（

Yes（
