### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by dfmjndm** [rafi1212122/PemukulPaku#9]
![image](https://github.com/rafi1212122/PemukulPaku/assets/57401901/8455b8ca-d025-40ab-a7be-eebcb8f75c18)
From the screenshot,my mongodb is running well，but when i ran the exe，i couldn‘t see the prompt “successfully connect to the mongodb” in the windows as usual. So the server didn't connect to the game finally maybe because of the lack of  database supports .
Here are some pictures of other windows, and I check the files in the turtior and make sure the files needed are in place .And in the former issues ,my windows 80 port is stucked by a kind of system program , now I have solved the problem so there is no other thread that stucked the 80/443 port.
![image](https://github.com/rafi1212122/PemukulPaku/assets/57401901/632c1840-fb6a-4f65-8c28-8328c682859f)
![image](https://github.com/rafi1212122/PemukulPaku/assets/57401901/8c085823-0ba2-400c-9ed0-2e8c4ed39109)
![image](https://github.com/rafi1212122/PemukulPaku/assets/57401901/649cdb1d-2f8e-4819-93d1-3009efc0455a)
And differ from my former successful experience ,this time when i get into the game, i saw the graph of captcha ,is there any thing wrong with proxy? the game server runs in port 16100 but in proxy.py i couldn't find it.
Waiting for any support . 

My game version is global region , ver 6.6, in windows platfrom

additionally, the mitmproxy-ca-cert.p12 was also installed

**Comment by cxfm666** [comment]
呃呃，有没有看见你控制台“选择”俩字?在控制台点下右键

**Comment by dfmjndm** [comment]
好的解决了
